# Generated by Django 4.1.7 on 2023-04-26 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_name', models.CharField(blank=True, max_length=200)),
                ('destination_name', models.CharField(blank=True, max_length=200)),
                ('departure_long', models.CharField(blank=True, max_length=200)),
                ('destination_lat', models.CharField(blank=True, max_length=200)),
                ('conditions', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_creator', to='Profiles.profile')),
                ('passengers', models.ManyToManyField(blank=True, to='Profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('seats', models.PositiveIntegerField(default='1')),
                ('is_approved', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='Profiles.profile')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='Rides.ride')),
            ],
        ),
    ]
